Week2
rakzeee/EP-JS-project pull request #2
Opened 2018-11-01 12:11 UTC by rakzeee

Added npm support
Project bundler
Configured development environment
Code transpilling support

2018-11-02 18:03 UTC, kos33rd requested changes
Необходимо поправить работу без глобально установленного `nodemon`, в остальном всё круто.

2018-11-02 18:03 UTC, kos33rd commented on crypto-tracker/package.json
> +{
В принципе, можно было бы все файлы из директории `crypto-tracker` поместить в корень проекта - это обычная практика.

2018-11-02 18:03 UTC, kos33rd commented on crypto-tracker/package.json
> +    "dev": "nodemon ./startServer.js",
При вызове `npm run dev` на машине, на которой не установлен `nodemon`, выдаётся ошибка:
```
"nodemon" не является внутренней или внешней командой
```

Нужно поправить.

2018-11-02 18:07 UTC, kos33rd approved these changes
Случайно заапрувил не туда :)

2018-11-02 18:08 UTC, kos33rd requested changes
Необходимо поправить работу без глобально установленного nodemon, в остальном всё круто.

2018-11-03 20:07 UTC, rakzeee commented on crypto-tracker/package.json
> +{
> В принципе, можно было бы все файлы из директории `crypto-tracker` поместить в корень проекта - это обычная практика.

готово

2018-11-06 07:41 UTC, kos33rd approved these changes

2018-11-06 07:43 UTC, merged